export const items = [
  'sport ⚽️',
  'muzyka 🎧',
  'gry 🎮',
  'fotografia 📸',
  'sztuka 🎭',
  'książki 📕',
  'biznes 📈',
  'netflix 🎥',
  'imprezy 🎉',
  'języki 🗣',
  'biologia 🧬',
  'informatyka 🧑‍💻',
  'siłownia 🏋️‍♀️',
  'matematyka 🔢',
  'gra na instrumentach 🎸',
  'fizyka ⚛️',
  'gotowanie 🍳',
  'historia 🏰',
  'podróże ✈️',
  'zwierzęta 🐾',
  'pieczenie 🍰',
  'bieganie 🏃‍♂️',
  'wos 🗽',
  'makjiaż 💄',
  'moda 🛍',
  'geografia 🌎',
  'technologia 🖥',
  'chemia 🧪',
  'rozwój osobisty 🏆',
  'śpiew 🎙',
  'medytacja 🧘‍♂️',
  'taniec 🩰',
  'malowanie 🎨',
  'filozofia 📖',
  'szycie 🪡',
  'programowanie 📟'
];
