name: Greetings | issues

on: issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          'PL: Hej! 👋 Dziękujemy za zgłoszenie nam problemu z aplikacją! Za niedługo ktoś zostanie przydzielony do tego błędu. 🙌'
          'EN: Hey! 👋 Thank you for dispatching this issue! As soon as we can, we will handle with it. 🙌'
