# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull requests | CI

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Running Node.js in version ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing packages...
      run: npm ci
    - name: Testing application...
      run: npm test
    - name: Testing (e2e) application...
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        project: ./src/e2e/
